Check if all states are covered
Deltares/Wflow.jl pull request #359
Opened 2024-02-13 16:21 UTC by JoostBuitink

## Issue addressed
Fixes #293 

## Explanation
Explain how you addressed the bug/feature request, what choices you made and why.

## Checklist
- [ ] Updated tests or added new tests
- [ ] Branch is up to date with `master`
- [ ] Tests & pre-commit hooks pass
- [ ] Updated documentation if needed
- [ ] Updated changelog.md if needed

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

2024-02-19 10:27 UTC, verseve requested changes
Looks overall good to me. Some code suggestions, mainly related to argument types, dispatch and couple of typos. Nice addition of extra tests for this functionality! 

Another general suggestion is to reformat the code after the review if multiple files without code changes (for the PR) are affected. This makes it easier to check what has been changed as part of the PR :smiley:.

2024-02-19 10:27 UTC, verseve commented on src/states.jl
> +function extract_required_states(config)
```suggestion
"""
    extract_required_states(config::Config)

Function to retrieve the required states, given the model configuration. The required states
are inferred from the model settings (mainly model_type, model options and routing types).
Returns as list of required states, in the same formats as the keys that are returned from the
`ncnames` function.
"""
function extract_required_states(config::Config)
```

2024-02-19 10:27 UTC, verseve commented on src/states.jl
> +end
```suggestion
"""
    add_to_required_states(required_states::Tuple, key_entry::Tuple, states::Union{Nothing,Tuple})

Function to iterate through the list of `states` and add these to the `required_states`
variable. This is a tuple of tuples, that contains the correct "prefix" to the state
category (provided by the `key_entry` variable). This is added in front of each element in
the list of `states`, and the `required_states` tuple is returned.
"""
function add_to_required_states(
    required_states::Tuple,
    key_entry::Tuple,
    states::Tuple,
)
    for state in states
        required_states = (required_states..., (key_entry..., state))
    end

    return required_states
end

add_to_required_states(required_states::Tuple, key_entry::Tuple, states::Nothing,) = required_states
```

I suggest to make use of dispatch in this case.

2024-02-19 10:27 UTC, verseve commented on docs/src/changelog.md
> +  warning in the logging), and the simulation will continue.
```suggestion
- Checks to see if all states are covered in the .toml file. If not all states are covered,
  an error is thrown. If there are more states specified than required, these states are
  ignored (with a warning in the logging), and the simulation will continue.
```

2024-02-19 14:28 UTC, JoostBuitink commented
Thanks for the review, and good suggestions! I have included them all in the latest version. And sorry for creating a messy PR with the formatting changes, I will pay attention to that next time ;)

2024-02-20 07:13 UTC, verseve approved these changes
LGTM!

2024-02-20 16:19 UTC, merged